### ISSUE TITLE
UniformTSDFVolume::Reset does not clear voxels

### ISSUE THREAD

**Issue by PieroV** [intel-isl/Open3D#1078]
**Describe the bug**
Calling `UniformTSDFVolume::Reset` won't actually reset the volume

**To Reproduce**
1. Create a UniformTSDFVolume and integrate some frames
2. Call `volume.Reset();`
3. Visualize somehow the volume, e.g. `open3d::visualization::DrawGeometries({ volume.ExtractPointCloud() });`

**Expected behavior**
I expect the volume to be empty.
In the previous example, I would expect an empty visualization window, but I still see the content up to the frames I integrated.

**Environment (please complete the following information):**
 - OS: Debian Testing (11/Bullseye)
 - Python version: 3.7.3 (but tested in C++)
 - Open3D version: last git commit
 - Is this remote workstation?: no
 - How did you install Open3D? build_from_source (GCC (Debian 8.3.0-6) 8.3.0)

**Additional context**
I think that overriding the `Clear` method also in `TSDFVoxel` (in `src/Open3D/Integration/UniformTSDFVolume.h`) would solve this. The problem is that the `voxels_` member is redefined, so the `Clear` of `Voxel` just clears its own voxels, but not the ones of the child class.
As a temporary solution I managed to solve the problem by calling `volume.voxel_grid_.voxels_.clear();` before `volume.Reset();`.

**Comment by yxlao** [comment]
Thanks @PieroV, fixed in https://github.com/intel-isl/Open3D/pull/1079. This is a design flaw.

**Comment by demul** [comment]
It seem that reset() still not actually reset volume
To Reproduce
```
volume = o3d.pipelines.integration.UniformTSDFVolume(
                length=5.0,
                resolution=500,
                sdf_trunc=0.010,
                color_type=o3d.pipelines.integration.TSDFVolumeColorType.RGB8)
volume.integrate(something)

before = np.asarray(volume.extract_volume_tsdf())
volume.reset()
after = np.asarray(volume.extract_volume_tsdf())

print(np.all(before == after))
```
