### ISSUE TITLE
Segmentation fault displaying mesh (two triangles) with texture in 0.10

### ISSUE THREAD

**Issue by saulzar** [intel-isl/Open3D#2089]
**Describe the bug**
Trying to display basic mesh with UVs and texture map causes segmentation fault. Similar code in 0.9 used to work (mesh.texture instead of mesh.textures).

It seems this has something to do with material ids, which it doesn't seem possible to add in python. If the mesh is first saved to file and loaded it will have material ids and display fine.

**To Reproduce**

```
import open3d
image = np.zeros((100, 100, 3), dtype=np.float32)

w, h = 10, 10
corners = np.array([
    [0, 0, 0],
    [w, 0, 0],
    [w, h, 0],
    [0, h, 0],            
])
triangles = np.array([[2, 1, 0], [0, 3, 2]])
mesh = open3d.geometry.TriangleMesh(open3d.utility.Vector3dVector(corners), open3d.utility.Vector3iVector(triangles))
   
uvs = [
    (1, 1), (1, 0), (0, 0),
    (0, 0), (0, 1), (1, 1)
]
mesh.triangle_uvs = open3d.utility.Vector2dVector(uvs)
image = open3d.geometry.Image(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
mesh.textures = [image]

open3d.visualization.draw_geometries([mesh])

```

**Expected behavior**
Draw square with image texture mapped to it. 

**Environment (please complete the following information):**
Ubuntu 18.04
Python 3.7
Open3d 0.10
Is this remote workstation?: no
How did you install Open3D? pip

**Comment by sadams207** [comment]
I commented on #1517 about this. Should have looked harder before commenting there. 
Seems like the material_ids attribute needs to be set, but there is no apparent way to do this in python.

**Comment by griegler** [comment]
@errissa and @prewettg are working on new bindings for this (for the new visualizer).

**Comment by RamyaThanga** [comment]
Is this issue fixed? Any update please?

**Comment by germanros1987** [comment]
@errissa what is the current state of this?

**Comment by errissa** [comment]
This is still an issue. Without access in Python to `TriangleMesh::triangle_material_ids_` it is not possible to programmatically texture a triangle mesh with the old visualizer.

**Comment by errissa** [comment]
This issue is now fixed and merged into master.

**Comment by MagJ1** [comment]
It somehow does not work for me. I use open3d version 0.14.1. I am a little frustrated. I just created one triangle, but still get the error message Segmentation fault: 11 

Am I allowed to put my code here, so one might check it? Or should I open a new thread? 

Help is much appreciated, thank you in advance.

**Comment by theNded** [comment]
@MagJ1 It is recommended to open a new issue and paste your code for easier tracking, since this has been closed. Thanks!
