### ISSUE TITLE
PyPi has open3d 0.12 only for Python 3.8 and earlier, not for 3.9

### ISSUE THREAD

**Issue by jackjansen** [intel-isl/Open3D#3065]
The entry for Open3D in pypi states it is compatible with Python 3.8 and earlier.

So if you use `pip install open3d` in Python 3.9 you get an error `Could not find a version that satisfies the requirement open3d`.

Is the current version of open3d really incompatible with Python 3.9? If so: any estimate when this could be fixed?

Or possibly this is just an oversight, and someone just forgot to update `setup.py` when Python 3.9 came out...

**Comment by jackjansen** [comment]
(Note that downgrading Python to 3.8 is less and less an option, now that Python 3.9 has been out for 4 months. For example, if you use `brew` on MacOS and you use other packages like libpcl then the brew formulas have already tied those packages to Python 3.9).

**Comment by ssheorey** [comment]
Python 3.9 support is planned soon. This is one blocker:
https://github.com/tensorflow/tensorflow/issues/44485

**Comment by jennifer-scale** [comment]
Any updates on this yet?

**Comment by ssheorey** [comment]
Tensorflow is planning to support Python 3.9 by the end of April. Open3D should be able to support Python 3.9 after that (i.e. **after** release 0.13).
In the mean time, please use `pyenv` or `conda` with `pip` to install and run Python 3.8 and other Python packages with Open3D.

**Comment by jackjansen** [comment]
@ssheorey wonderful! 

(note that for me at least the issue isn't with open3d per se, but with dependency on multiple packages. So now I have a dependency on open3d, which means I have to use Python <= 3.8 and a dependency on another package which requires python 3.9 (for the most recent version, of which I need a specific feature). I'm hoping the Python stable API efforts will come to fruition soon, that should fix most of this.)

**Comment by raaaaaymond** [comment]
So as of today, although [their website](https://www.tensorflow.org/install) doesn't officially say they support Python 3.9, I've just tried installing it on my Python 3.9.5 and it worked. (Windows.) Given this, is Open3D able to support Python 3.9 now?

**Comment by ssheorey** [comment]
We would prefer to wait for the official support, since this likely means they are ironing out the last few bugs. We would encourage you to try building Open3D + Tensorflow with Python 3.9 and let us know if there are any issues. Please use Python 3.9.1 or later due to this undefined behavior issue with Pybind11:
https://github.com/python/cpython/pull/22670

**Comment by erkil1452** [comment]
It seems Python 3.9 is now officially supported for TensorFlow 2.5+.

**Comment by raymondmengji** [comment]
Hi, I'm wondering what is the current status of open3d for Python 3.9.x?

**Comment by felixbors** [comment]
Ubuntu is pushing the upgrade as of Aug 2021 to 21;  this comes with Python 3.9.   open3d still does not install with pip...
any plans to release it?

**Comment by vadimkantorov** [comment]
Blender 2.93 ships with Python 3.9. For simplicity I wanted to install open3d into its Python distribution - to no avail :(

**Comment by ssheorey** [comment]
Python 3.9 development (latest master) Python wheels are available from here:
http://www.open3d.org/docs/latest/getting_started.html#development-version-pip

**Comment by wangsen1312** [comment]
when I tried 
"pip install --user --pre https://storage.googleapis.com/open3d-releases-master/python-wheels/open3d-0.13.0+61e8b79-cp39-cp39-linux_x86_64.whl"
It shows error and show no such whl

**Comment by ssheorey** [comment]
Please retry after some time. The website update and wheel uploading may happen at slightly different times.

**Comment by wangsen1312** [comment]
@ssheorey  I have met the problem. When I use pip to install the download .whl. It shows that install sucessfully. But when i import open3d. it stucks and nothing happens

**Comment by Niko-La** [comment]
any update on python 3.9 windows 10?

the equivlent of  `"pip install --user --pre https://storage.googleapis.com/open3d-releases-master/python-wheels/open3d-0.13.0+61e8b79-cp39-cp39-linux_x86_64.whl"`

**Comment by ssheorey** [comment]
Development Python wheels for all platforms are available here:
http://www.open3d.org/docs/latest/getting_started.html#development-version-pip

**Comment by clbarnes** [comment]
Open3d's pypi releases are now 2 python versions behind and so it can't really be used as a core dependency of any modern code. The blocking Tensorflow issue seems to have been resolved in May, and Tensorflow has been shipping releases with 3.9 support for over a year at this point. The README of this repo says that 3.9 is supported but there are no 3.9 wheels in the last couple of releases. Any chance of them coming soon?

**Comment by ga1i13o** [comment]
I still have this issue by the way, on Python 3.9.6 I still get `ERROR: Could not find a version that satisfies the requirement open3d (from versions: none)` from pip
